// Create a Jenkinsfile pipeline script that pulls the messaging app’s code from GitHub, installs dependencies, runs tests using pytest, and generates a report

// Ensure to add Credentials for GitHub
pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-credentials', url: 'https://github.com/drkyuka/alx-backend-python.git'
            }
        }

        stage('Check Credentials'){
            steps {
                sh ''' 
                    git branch --show-current
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    pipenv run pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                pipenv run pytest --junitxml=report.xml
            }
        }

        stage('Publish Report') {
            steps {
                junit 'report.xml'
            }
        }
    }
}