# Generated by Django 5.2.2 on 2025-06-12 22:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False, help_text='Indicates whether the message has been edited'),
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the message history entry', primary_key=True, serialize=False, unique=True)),
                ('edited_content', models.TextField(help_text='Content of the message after editing')),
                ('edited_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was edited')),
                ('edited_by', models.ForeignKey(help_text='User who edited the message', on_delete=django.db.models.deletion.CASCADE, related_name='messaging_edited_messages', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(help_text='Message that was edited', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='messaging.message')),
            ],
            options={
                'verbose_name': 'Message History',
                'verbose_name_plural': 'Message Histories',
                'db_table': 'messaging_message_history',
            },
        ),
    ]
