# Generated by Django 5.2.3 on 2025-06-13 23:57

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_parent_message'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('unread', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False, help_text='Indicates whether the message has been read'),
        ),
    ]
