-- SQLite script to create users table and populate with sample data

-- Create the users table with proper fields
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    date_created DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Delete existing data if any (to avoid duplicates when running multiple times)
DELETE FROM users;

-- Reset the autoincrement counter
DELETE FROM sqlite_sequence WHERE name='users';

-- Insert 100 sample users
INSERT INTO users (firstname, lastname) VALUES
('John', 'Doe'),
('Jane', 'Smith'),
('Michael', 'Johnson'),
('Emily', 'Williams'),
('David', 'Brown'),
('Sarah', 'Jones'),
('Robert', 'Miller'),
('Jennifer', 'Davis'),
('William', 'Garcia'),
('Elizabeth', 'Rodriguez'),
('Richard', 'Wilson'),
('Barbara', 'Martinez'),
('Joseph', 'Anderson'),
('Susan', 'Taylor'),
('Thomas', 'Thomas'),
('Margaret', 'Hernandez'),
('Charles', 'Moore'),
('Jessica', 'Martin'),
('Daniel', 'Jackson'),
('Nancy', 'Thompson'),
('Matthew', 'White'),
('Lisa', 'Lopez'),
('Anthony', 'Lee'),
('Karen', 'Gonzalez'),
('Mark', 'Harris'),
('Betty', 'Clark'),
('Donald', 'Lewis'),
('Ashley', 'Robinson'),
('Steven', 'Walker'),
('Patricia', 'Perez'),
('Andrew', 'Hall'),
('Linda', 'Young'),
('George', 'Allen'),
('Mary', 'Sanchez'),
('Kenneth', 'Wright'),
('Helen', 'King'),
('Joshua', 'Scott'),
('Melissa', 'Green'),
('Edward', 'Baker'),
('Donna', 'Adams'),
('Brian', 'Nelson'),
('Carol', 'Hill'),
('Ronald', 'Ramirez'),
('Laura', 'Campbell'),
('Kevin', 'Mitchell'),
('Amanda', 'Roberts'),
('Timothy', 'Carter'),
('Deborah', 'Phillips'),
('Jason', 'Evans'),
('Sharon', 'Turner'),
('Jeffrey', 'Torres'),
('Ruth', 'Parker'),
('Ryan', 'Collins'),
('Kimberly', 'Edwards'),
('Gary', 'Stewart'),
('Michelle', 'Flores'),
('Nicholas', 'Morris'),
('Dorothy', 'Nguyen'),
('Eric', 'Murphy'),
('Cynthia', 'Rivera'),
('Stephen', 'Cook'),
('Kathleen', 'Rogers'),
('Jonathan', 'Morgan'),
('Amy', 'Peterson'),
('Justin', 'Cooper'),
('Shirley', 'Reed'),
('Brandon', 'Bailey'),
('Catherine', 'Bell'),
('Paul', 'Gomez'),
('Angela', 'Kelly'),
('Johnny', 'Howard'),
('Virginia', 'Ward'),
('Raymond', 'Cox'),
('Pamela', 'Diaz'),
('Samuel', 'Richardson'),
('Martha', 'Wood'),
('Benjamin', 'Watson'),
('Debra', 'Brooks'),
('Gregory', 'Bennett'),
('Carolyn', 'Gray'),
('Jerry', 'James'),
('Judith', 'Reyes'),
('Dennis', 'Cruz'),
('Janet', 'Hughes'),
('Tyler', 'Price'),
('Diane', 'Myers'),
('Walter', 'Long'),
('Teresa', 'Foster'),
('Peter', 'Sanders'),
('Alice', 'Ross'),
('Aaron', 'Morales'),
('Anna', 'Powell'),
('Kyle', 'Sullivan'),
('Marie', 'Russell'),
('Harold', 'Ortiz'),
('Brenda', 'Jenkins'),
('Adam', 'Gutierrez'),
('Gloria', 'Perry'),
('Lawrence', 'Barnes'),
('Frances', 'Fisher');