# Configure a GitHub Actions workflow that runs the Django tests on every push and pull request.

# Ensure the workflow installs necessary dependencies and sets up a MySQL database for running tests

name: Django Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: messaging_app_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost" 
          --health-interval=30s
          --health-timeout=5s 
          --health-retries=3
    steps:
      - name: setup python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: install dependencies using pipenv
        run: |
          sudo apt-get update
          sudo apt-get install -y pipenv
          pipenv install -r requirements.txt

      - name: run django migrations
        run: |
          pipenv run python manage.py makemigrations
          pipenv run python manage.py migrate

      - name: run tests
        run: |
          pipenv run python manage.py test --settings=messaging_app.settings.test