# Set up a GitHub Actions workflow that builds a Docker image for the messaging app.

# Push the Docker image to Docker Hub

# Use GitHub Actions’ secrets feature to store your Docker credentials securely

name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t drkingkyavoni/messaging_app:v1.0.0 --push .

      - name: Logout from Docker Hub
        run: |
          docker logout