# Generated by Django 5.2.1 on 2025-05-31 18:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.UUIDField(default=uuid.UUID('056dba2f-fa70-4726-8d8a-5e90c7feb873'), editable=False, help_text='Unique identifier for the conversation', primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.UUIDField(default=uuid.UUID('544fae40-a116-402f-b6ee-be5dd958e91b'), editable=False, help_text='Unique identifier for the user', primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(help_text='Email address of the user', max_length=254, unique=True)),
                ('password', models.CharField(help_text='Password for the user account', max_length=128)),
                ('first_name', models.CharField(help_text='First name of the user', max_length=30)),
                ('last_name', models.CharField(help_text='Last name of the user', max_length=30)),
                ('phone_number', models.CharField(help_text='Phone number of the user', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.UUID('ff5a2f33-c492-4b07-8a29-fe99274d45c4'), editable=False, help_text='Unique identifier for the message', primary_key=True, serialize=False, unique=True)),
                ('message_body', models.TextField(help_text='Content of the message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was created')),
                ('conversation', models.ForeignKey(help_text='Conversation to which the message belongs', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.conversation')),
                ('receiver', models.ForeignKey(help_text='User who received the message', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='chats.user')),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='chats.user')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(help_text='Users participating in the conversation', to='chats.user'),
        ),
    ]
